// <auto-generated />
namespace BaseballAPI.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class WinLoss : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WinLoss));
        
        string IMigrationMetadata.Id
        {
            get { return "202204181311341_WinLoss"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
